aleksis/apps/alsijil/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("lesson", views.register_object, {"model": "lesson"}, name="lesson_period"),
    path(
        "lesson/<int:year>/<int:week>/<int:id_>",
        views.register_object,
        {"model": "lesson"},
        name="lesson_period",
    ),
    path(
        "extra_lesson/<int:id_>/",
        views.register_object,
        {"model": "extra_lesson"},
        name="extra_lesson",
    ),
    path("event/<int:id_>/", views.register_object, {"model": "event"}, name="event",),
    path("week/", views.week_view, name="week_view"),
    path("week/<int:year>/<int:week>/", views.week_view, name="week_view_by_week"),
    path("week/year/cw/", views.week_view, name="week_view_placeholders"),
    path("week/<str:type_>/<int:id_>/", views.week_view, name="week_view"),
    path("week/year/cw/<str:type_>/<int:id_>/", views.week_view, name="week_view_placeholders",),
    path(
        "week/<int:year>/<int:week>/<str:type_>/<int:id_>/",
        views.week_view,
        name="week_view_by_week",
    ),
    path("print/group/<int:id_>", views.full_register_group, name="full_register_group"),
    path("groups/", views.my_groups, name="my_groups"),
    path("groups/<int:pk>/", views.StudentsList.as_view(), name="students_list"),
    path("persons/", views.my_students, name="my_students"),
    path("persons/<int:id_>/", views.overview_person, name="overview_person"),
    path("me/", views.overview_person, name="overview_me"),
    path(
        "notes/<int:pk>/delete/",
        views.DeletePersonalNoteView.as_view(),
        name="delete_personal_note",
    ),
    path("absence/new/<int:id_>/", views.register_absence, name="register_absence"),
    path("extra_marks/", views.ExtraMarkListView.as_view(), name="extra_marks"),
    path("extra_marks/create/", views.ExtraMarkCreateView.as_view(), name="create_extra_mark",),
    path("extra_marks/<int:pk>/edit/", views.ExtraMarkEditView.as_view(), name="edit_extra_mark",),
    path(
        "extra_marks/<int:pk>/delete/",
        views.ExtraMarkDeleteView.as_view(),
        name="delete_extra_mark",
    ),
    path("excuse_types/", views.ExcuseTypeListView.as_view(), name="excuse_types"),
    path("excuse_types/create/", views.ExcuseTypeCreateView.as_view(), name="create_excuse_type",),
    path(
        "excuse_types/<int:pk>/edit/", views.ExcuseTypeEditView.as_view(), name="edit_excuse_type",
    ),
    path(
        "excuse_types/<int:pk>/delete/",
        views.ExcuseTypeDeleteView.as_view(),
        name="delete_excuse_type",
    ),
    path("group_roles/", views.GroupRoleListView.as_view(), name="group_roles"),
    path("group_roles/create/", views.GroupRoleCreateView.as_view(), name="create_group_role"),
    path("group_roles/<int:pk>/edit/", views.GroupRoleEditView.as_view(), name="edit_group_role",),
    path(
        "group_roles/<int:pk>/delete/",
        views.GroupRoleDeleteView.as_view(),
        name="delete_group_role",
    ),
    path(
        "groups/<int:pk>/group_roles/",
        views.AssignedGroupRolesView.as_view(),
        name="assigned_group_roles",
    ),
    path(
        "groups/<int:pk>/group_roles/assign/",
        views.AssignGroupRoleView.as_view(),
        name="assign_group_role",
    ),
    path(
        "groups/<int:pk>/group_roles/<int:role_pk>/assign/",
        views.AssignGroupRoleView.as_view(),
        name="assign_group_role",
    ),
    path(
        "group_roles/assignments/<int:pk>/edit/",
        views.GroupRoleAssignmentEditView.as_view(),
        name="edit_group_role_assignment",
    ),
    path(
        "group_roles/assignments/<int:pk>/stop/",
        views.GroupRoleAssignmentStopView.as_view(),
        name="stop_group_role_assignment",
    ),
    path(
        "group_roles/assignments/<int:pk>/delete/",
        views.GroupRoleAssignmentDeleteView.as_view(),
        name="delete_group_role_assignment",
    ),
    path(
        "group_roles/assignments/assign/",
        views.AssignGroupRoleMultipleView.as_view(),
        name="assign_group_role_multiple",
    ),
    path("all/", views.AllRegisterObjectsView.as_view(), name="all_register_objects"),
]

aleksis/apps/alsijil/forms.py
from datetime import datetime, timedelta
from typing import Optional, Sequence

from django import forms
from django.core.exceptions import ValidationError
from django.db.models import Count, Q
from django.http import HttpRequest
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from django_select2.forms import ModelSelect2MultipleWidget, ModelSelect2Widget, Select2Widget
from guardian.shortcuts import get_objects_for_user
from material import Fieldset, Layout, Row

from aleksis.apps.chronos.managers import TimetableType
from aleksis.apps.chronos.models import Subject, TimePeriod
from aleksis.core.forms import ActionForm, ListActionForm
from aleksis.core.models import Group, Person, SchoolTerm
from aleksis.core.util.core_helpers import get_site_preferences
from aleksis.core.util.predicates import check_global_permission

from .actions import (
    delete_personal_note,
    mark_as_excuse_type_generator,
    mark_as_excused,
    mark_as_unexcused,
    send_request_to_check_entry,
)
from .models import (
    ExcuseType,
    ExtraMark,
    GroupRole,
    GroupRoleAssignment,
    LessonDocumentation,
    PersonalNote,
)


class LessonDocumentationForm(forms.ModelForm):
    class Meta:
        model = LessonDocumentation
        fields = ["topic", "homework", "group_note"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["homework"].label = _("Homework for the next lesson")


class PersonalNoteForm(forms.ModelForm):
    class Meta:
        model = PersonalNote
        fields = ["absent", "late", "excused", "excuse_type", "extra_marks", "remarks"]

    person_name = forms.CharField(disabled=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["person_name"].widget.attrs.update(
            {"class": "alsijil-lesson-personal-note-name"}
        )
        self.fields["person_name"].widget = forms.HiddenInput()

        if self.instance and getattr(self.instance, "person", None):
            self.fields["person_name"].initial = str(self.instance.person)


class SelectForm(forms.Form):
    layout = Layout(Row("group", "teacher"))

    group = forms.ModelChoiceField(
        queryset=None, label=_("Group"), required=False, widget=Select2Widget,
    )
    teacher = forms.ModelChoiceField(
        queryset=None, label=_("Teacher"), required=False, widget=Select2Widget,
    )

    def clean(self) -> dict:
        data = super().clean()

        if data.get("group") and not data.get("teacher"):
            type_ = TimetableType.GROUP
            instance = data["group"]
        elif data.get("teacher") and not data.get("group"):
            type_ = TimetableType.TEACHER
            instance = data["teacher"]
        elif not data.get("teacher") and not data.get("group"):
            return data
        else:
            raise ValidationError(_("You can't select a group and a teacher both."))

        data["type_"] = type_
        data["instance"] = instance
        return data

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super().__init__(*args, **kwargs)

        person = self.request.user.person

        group_qs = Group.get_groups_with_lessons()

        # Filter selectable groups by permissions
        if not check_global_permission(self.request.user, "alsijil.view_week"):
            # 1) All groups the user is allowed to see the week view by object permissions
            # 2) All groups the user is a member of an owner of
            group_qs = (
                group_qs.filter(
                    pk__in=get_objects_for_user(
                        self.request.user, "core.view_week_class_register_group", Group
                    ).values_list("pk", flat=True)
                )
            ).union(group_qs.filter(Q(members=person) | Q(owners=person)))

        # Flatten query by filtering groups by pk
        self.fields["group"].queryset = Group.objects.filter(
            pk__in=list(group_qs.values_list("pk", flat=True))
        )

        teacher_qs = Person.objects.annotate(lessons_count=Count("lessons_as_teacher")).filter(
            lessons_count__gt=0
        )

        # Filter selectable teachers by permissions
        if not check_global_permission(self.request.user, "alsijil.view_week"):
            # If the user hasn't the global permission,
            # the user is only allowed to see his own person
            teacher_qs = teacher_qs.filter(pk=person.pk)

        self.fields["teacher"].queryset = teacher_qs


PersonalNoteFormSet = forms.modelformset_factory(
    PersonalNote, form=PersonalNoteForm, max_num=0, extra=0
)


class RegisterAbsenceForm(forms.Form):
    layout = Layout(
        Fieldset("", Row("date_start", "date_end"), Row("from_period", "to_period")),
        Fieldset("", Row("absent", "excused"), Row("excuse_type"), Row("remarks")),
    )
    date_start = forms.DateField(label=_("Start date"), initial=datetime.today)
    date_end = forms.DateField(label=_("End date"), initial=datetime.today)
    from_period = forms.ChoiceField(label=_("Start period"))
    to_period = forms.ChoiceField(label=_("End period"))
    absent = forms.BooleanField(label=_("Absent"), initial=True, required=False)
    excused = forms.BooleanField(label=_("Excused"), initial=True, required=False)
    excuse_type = forms.ModelChoiceField(
        label=_("Excuse type"),
        queryset=ExcuseType.objects.all(),
        widget=Select2Widget,
        required=False,
    )
    remarks = forms.CharField(label=_("Remarks"), max_length=30, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        period_choices = TimePeriod.period_choices

        self.fields["from_period"].choices = period_choices
        self.fields["to_period"].choices = period_choices
        self.fields["from_period"].initial = TimePeriod.period_min
        self.fields["to_period"].initial = TimePeriod.period_max


class ExtraMarkForm(forms.ModelForm):
    layout = Layout("short_name", "name")

    class Meta:
        model = ExtraMark
        fields = ["short_name", "name"]


class ExcuseTypeForm(forms.ModelForm):
    layout = Layout("short_name", "name")

    class Meta:
        model = ExcuseType
        fields = ["short_name", "name"]


class PersonOverviewForm(ActionForm):
    def get_actions(self):
        return (
            [mark_as_excused, mark_as_unexcused]
            + [
                mark_as_excuse_type_generator(excuse_type)
                for excuse_type in ExcuseType.objects.all()
            ]
            + [delete_personal_note]
        )


class GroupRoleForm(forms.ModelForm):
    layout = Layout("name", "icon", "colour")

    class Meta:
        model = GroupRole
        fields = ["name", "icon", "colour"]


class AssignGroupRoleForm(forms.ModelForm):
    layout_base = ["groups", "person", "role", Row("date_start", "date_end")]

    groups = forms.ModelMultipleChoiceField(
        label=_("Group"),
        required=True,
        queryset=Group.objects.all(),
        widget=ModelSelect2MultipleWidget(
            model=Group,
            search_fields=["name__icontains", "short_name__icontains"],
            attrs={"data-minimum-input-length": 0, "class": "browser-default",},
        ),
    )
    person = forms.ModelChoiceField(
        label=_("Person"),
        required=True,
        queryset=Person.objects.all(),
        widget=ModelSelect2Widget(
            model=Person,
            search_fields=[
                "first_name__icontains",
                "last_name__icontains",
                "short_name__icontains",
            ],
            attrs={"data-minimum-input-length": 0, "class": "browser-default"},
        ),
    )

    def __init__(self, request, *args, **kwargs):
        self.request = request
        initial = kwargs.get("initial", {})

        # Build layout with or without groups field
        base_layout = self.layout_base[:]
        if "groups" in initial:
            base_layout.remove("groups")
        self.layout = Layout(*base_layout)

        super().__init__(*args, **kwargs)

        if "groups" in initial:
            self.fields["groups"].required = False

        # Filter persons and groups by permissions
        if not self.request.user.has_perm("alsijil.assign_grouprole"):  # Global permission
            persons = Person.objects
            if initial.get("groups"):
                persons = persons.filter(member_of__in=initial["groups"])
            if get_site_preferences()["alsijil__group_owners_can_assign_roles_to_parents"]:
                persons = persons.filter(
                    Q(member_of__owners=self.request.user.person)
                    | Q(children__member_of__owners=self.request.user.person)
                )
            else:
                persons = persons.filter(member_of__owners=self.request.user.person)
            self.fields["person"].queryset = persons

            if "groups" not in initial:
                groups = Group.objects.for_current_school_term_or_all().filter(
                    owners=self.request.user.person
                )
                self.fields["groups"].queryset = groups

    def clean_groups(self):
        """Ensure that only permitted groups are used."""
        return self.initial["groups"] if "groups" in self.initial else self.cleaned_data["groups"]

    class Meta:
        model = GroupRoleAssignment
        fields = ["groups", "person", "role", "date_start", "date_end"]


class GroupRoleAssignmentEditForm(forms.ModelForm):
    class Meta:
        model = GroupRoleAssignment
        fields = ["date_start", "date_end"]


class FilterRegisterObjectForm(forms.Form):
    """Form for filtering register objects in ``RegisterObjectTable``."""

    layout = Layout(
        Row("school_term", "date_start", "date_end"), Row("has_documentation", "group", "subject")
    )

aleksis/apps/alsijil/templates/alsijil/absences/register.html
{# -*- engine:django -*- #}
{% extends "core/base.html" %}
{% load material_form i18n static %}

{% block browser_title %}{% blocktrans %}Register absence{% endblocktrans %}{% endblock %}
{% block page_title %}{% blocktrans %}Register absence{% endblocktrans %}{% endblock %}

{% block content %}
  <h6>{% trans "Person" %}: {{ person }}</h6>

  <form method="post">
    {% csrf_token %}
    {% form form=register_absence_form %}{% endform %}
    {% include "core/partials/save_button.html" %}
  </form>

  <script>
    $(document).ready(function () {
      $("#id_date_start").change(function () {
        $("#id_date_end").val($("#id_date_start").val());
        initDatePicker("#id_date_end");
      });
    });
  </script>
{% endblock %}

aleksis/apps/alsijil/templates/alsijil/absences/register_confirm.html
{# -*- engine:django -*- #}
{% extends "core/base.html" %}
{% load material_form i18n static %}

{% block browser_title %}{% blocktrans %}Confirm: Register absence{% endblocktrans %}{% endblock %}
{% block page_title %}{% blocktrans %}Confirm: Register absence{% endblocktrans %}{% endblock %}

{% block content %}
  <p class="flow-text">
    {% blocktrans %}
      Do you really want to register the following absence?
    {% endblocktrans %}
  </p>
  <div class="card">
    <div class="card-content">
      <div class="card-title">
        {{ person }}
      </div>
      <div class="collection">
        <div class="collection-item">
          <i class="material-icons left">date_range</i>
          {{ form_data.date_start }}, {{ form_data.from_period }}. – {{ form_data.date_end }}, {{ form_data.to_period }}.
          {% if form_data.date_start != form_data.date_end %}
            <figure class="alert warning">
              <i class="material-icons left">warning</i>
              {% blocktrans %}
                As the length of this absence is longer than one day,
                please double check the correctness of your entry.
              {% endblocktrans %}
            </figure>
          {% endif %}
        </div>
        <div class="collection-item">
          <i class="material-icons left">list</i>
          {% blocktrans with count=affected_lessons %} {{ count }} affected lessons {% endblocktrans %}
          {% if affected_lessons == 0 %}
            <div class="alert error">
              <div>
                <i class="material-icons left">error</i>
                {% blocktrans %}
                  There are no affected lessons. Registering this absence won't have any effect.
                {% endblocktrans %}
              </div>
            </div>
          {% endif %}
        </div>
        <div class="collection-item">
          <i class="material-icons left">label</i>
          {% if form_data.absent %}
            <span class="chip red white-text">{% trans "Absent" %}</span>
            {% if form_data.excused and form_data.excuse_type %}
              <span class="chip green white-text">{{ form_data.excuse_type.name }}</span>
            {% elif form_data.excused %}
              <span class="chip green white-text">{% trans "Excused" %}</span>
            {% endif %}
          {% else %}
            {% trans "Reset status to 'not absent'" %}
          {% endif %}
        </div>
        {% if form_data.remarks %}
          <div class="collection-item">
            <i class="material-icons left">edit</i>
            {{ form_data.remarks }}
          </div>
        {% endif %}
      </div>
    </div>
  </div>

  <form method="post">
    {% csrf_token %}
    <div class="hide">
      {% form form=form %}{% endform %}
    </div>
    <input type="hidden" name="confirmed" value="1">
    {% include "core/partials/save_button.html" %}
    <a class="btn red waves-effect waves-light" href="{% url "register_absence" person.pk %}">
      <i class="material-icons left">cancel</i>
      {% trans "Cancel" %}
    </a>
  </form>
{% endblock %}